spring:
  application:
    name: TMurder
  port: 8080
  thymeleaf:
    cache: false
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false
management:
  security:
    enabled: false
server:
  context-path: /index